[mysql]
host = "mysql-3a9d2f2b-oms-12-gegis.i.aivencloud.com"
port = 28393
database = "outage_management"  # or "defaultdb" if you're using that
user = "avnadmin"
password = "AVNS_bsnVINt_C3zX7eA7Mai"
